# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Conclave Arcanum
email: your-email@domain.com
description: 436f6e636c61766520617263616e756d20b7206f7264696e656d206465206368616f20b7206368616f7320657374206f7264696e656d20b720497461206d756c746920756e756d206465206d756c746973
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://conclavearcanum.github.io/" # the base hostname & protocol for your site
twitter_username: ConclaveArcanum
github_username:  ConclaveArcanum

# Build settings
markdown: kramdown
